### PR TITLE
[PRA-134] Add py4j dependency to PYTHONPATH in rock image

### LINKED ISSUE #179: Cannot import `pyspark` from inside the Charmed Spark image container due to missing py4j
Importing `pyspark` from inside a pod created from Charmed Spark OCI image fails with an error, complaining that `py4j` is missing. However, the import is successful when imported from inside the `spark-client.pyspark` shell.

Steps to Replicate:

1. `microk8s ctr image pull ghcr.io/canonical/charmed-spark:3.5-22.04_edge`
2. `microk8s kubectl run spark-pod --image=ghcr.io/canonical/charmed-spark:3.5-22.04_edge`
3. `microk8s kubectl exec -it spark-pod --  bash`
4. Open `python3` shell

```python
>>> import pyspark
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/spark/python/pyspark/__init__.py", line 58, in <module>
    from pyspark.conf import SparkConf
  File "/opt/spark/python/pyspark/conf.py", line 23, in <module>
    from py4j.java_gateway import JVMView, JavaObject
ModuleNotFoundError: No module named 'py4j'
```

Further context:

Upon further inspection, I inspected `PYTHONPATH` in both cases (in `spark-client.pyspark` shell and inside container pod), the following were the results:
```bash
# in pyspark shell
/snap/spark-client/84/opt/spark/python/lib/py4j-0.10.9.7-src.zip:/snap/spark-client/84/opt/spark/python/:/snap/spark-client/84/python:/snap/spark-client/84/lib/python3.10/site-packages:

# inside the container
/opt/spark/python:/opt/spark8t/python/dist:/usr/lib/python3.10/site-packages
```

The `PYTHONPATH` in the pyspark shell contains the path to `py4j`, but the one inside the container does not. For the pyspark-shell, it is being added [via this line](https://github.com/apache/spark/blob/master/bin/pyspark#L80C49-L80C50) upstream, however for the container, we don't have it added in the rockcraft `PYTHONPATH` environment variables.

Suggested Fix:
One suggested fix would be to add the path to `py4j` (which exists at `/opt/spark/python/lib` directory in the image) to the `PYTHONPATH` environment variable [here](https://github.com/canonical/charmed-spark-rock/blob/3.5/edge/images/charmed-spark/rockcraft.yaml#L28) in the rockcraft.yaml file.

### PR DESCRIPTION
**Pull request by theoctober19th**
Fixes #179 

In this PR, we add a soft link pointing to the py4j dependency to a static path, and add that path to the PYTHONPATH. This will ensure that the py4j zip will be in path even if the version of Py4j changes, without changing the code again.

### CODE REVIEW

File: tests/integration/integration-tests.sh [hunk 1]
```diff
@@ -653,10 +654,34 @@ run_pyspark_in_pod() {
...
 }
 
-test_pyspark_in_pod() {
-  run_pyspark_in_pod $NAMESPACE spark
+test_pyspark_shell_in_pod() {
+  run_pyspark_shell_in_pod $NAMESPACE spark
+}
+
+
+import_pyspark_from_python_runtime_in_pod() {
```
Comment (deusebio) [inline tests/integration/integration-tests.sh:662]: **praise** simple and effective!

**Review by deusebio — APPROVED** [review]
Looks very good! This was indeed a weak nerve! Great job at finding this and fixing the issue. Very minimal and effective PR!

**Review by welpaolo — APPROVED** [review]
LGTM

File: tests/integration/integration-tests-gpu.sh [hunk 2]
```diff
@@ -315,6 +315,31 @@ test_sql_gpu_example_in_pod() {
...
+  echo "import_pyspark_from_python_runtime_in_pod ${1} ${2}"
+
+  NAMESPACE=$1
+  USERNAME=$2
+
+  out=$(kubectl -n "$NAMESPACE" exec testpod -- python3 -c 'import py4j; import pyspark;' 2> >(tee /tmp/err.log))
+  rc=$?
+
+  if [[ $rc -ne 0 || -s /tmp/err.log ]]; then
+      echo "Canont import pyspark from inside pod:"
```
Comment (Batalex) [inline tests/integration/integration-tests-gpu.sh:330]:
```suggestion
      echo "Cannot import pyspark from inside pod:"
```

File: tests/integration/integration-tests.sh [hunk 3]
```diff
@@ -653,10 +654,34 @@ run_pyspark_in_pod() {
...
+  echo "import_pyspark_from_python_runtime_in_pod ${1} ${2}"
+
+  NAMESPACE=$1
+  USERNAME=$2
+
+  out=$(kubectl -n "$NAMESPACE" exec testpod -- python3 -c 'import py4j; import pyspark;' 2> >(tee /tmp/err.log))
+  rc=$?
+
+  if [[ $rc -ne 0 || -s /tmp/err.log ]]; then
+      echo "Canont import pyspark from inside pod:"
```
Comment (Batalex) [inline tests/integration/integration-tests.sh:672]:
```suggestion
      echo "Cannot import pyspark from inside pod:"
```

**Review by Batalex — APPROVED** [review]
LGTM, great job!

I found a couple of typos, but honestly it's up to you if you want to go through CI again just for two typos in the tests
